### PR TITLE
Move parse method into instance

### PR DESCRIPTION
**Pull request by ened**
.. and some basic tests & documentation.

### CODE REVIEW

**Comment by nashfive** [comment]
Thanks again for the PR. 
But I'd like to move all static to instance methods in one go. Can you also switch the other methods to being instance ones? I can do it on my side, I have some free time. 
And since it will break the current plugin API, it should be done in a new major version : 1.0.0.

**Comment by nashfive** [comment]
My bad about the versioning... in Dart, we can bump the minor, so a `0.6.0` would suffice. I am doing it right now ;)

**Comment by ened** [comment]
@nashfive , ok great, please go ahead. There is a extra test here which (among the missing ones :)) should be in the project at some point..

**Comment by nashfive** [comment]
@ened Which tests are you thinking about ?

**Comment by ened** [comment]
@nashfive https://github.com/nashfive/phone_number/pull/15/files#diff-729897e7a7820b9febd8c9e58b1d38ceR16 - that one could be used as a template.

**Comment by nashfive** [comment]
Implemented in #17

**Pull request closed without merging**
