### PR TITLE
Android embedding v2

### PR DESCRIPTION
**Pull request by ened**
This migrates the plugin to Flutters V2 Android embedding.
As part of the migration, E2E tests were added and can be used to verify the functionality on the actual target device.
Bumps version to 0.6.1

### CODE REVIEW

**Comment by nashfive** [comment]
@ened Thanks for this PR!
Just a quick question, I haven't had the time to look into this new android plugin engine thing, but is it a breaking change?

**Comment by ened** [comment]
@nashfive it's not breaking, which is verified by the E2E test in example/android.
You can run those tests (which verify the plugin works with old and new embedding) by following the steps here: https://pub.dev/packages/e2e#android-device-testing.

The major improvement on this PR is the addition of E2E testing in general. You will be able to write tests that verify the actual libPhonenumber calls on end devices.

**Comment by nashfive** [comment]
Thanks, I was thinking more about the tooling and the sdk. But I guess that the `pub get` command will handle that.

**Comment by ened** [comment]
Ah, you may be referring to this part:
```
environment:
   sdk: ">=2.3.0 <3.0.0"
   flutter: ">=1.12.13+hotfix.6 <2.0.0"
``` 

And yes, pub will handle. Note that Flutter 1.12.13 is the current stable version and 1.12.13+hotfix.6 is the version which is recommended for E2E test integration (details here: https://flutter.dev/docs/development/packages-and-plugins/plugin-api-migration).

**Pull request merged**
